# Monochrome for Kitty
# Ported from the pinned NvChad/base46 monochrome theme.

foreground #bfc5d0
background #101010

selection_foreground #ced4df
selection_background #2e2e2e

cursor #ced4df
cursor_text_color #101010

# Black
color0  #1a1a1a
color8  #4c4c4c

# Red
color1  #ec8989
color9  #eca8a8

# Green
color2  #c9d36a
color10 #eff6ab

# Yellow
color3  #ffe6b5
color11 #eff6ab

# Blue
color4  #8abae1
color12 #a5c6e1

# Magenta
color5  #e1bee9
color13 #db9fe9

# Cyan
color6  #9aafe6
color14 #dfdfda

# White
color7  #d8dee9
color15 #ced4df

# Tabs and borders
active_tab_foreground #ced4df
active_tab_background #242424
inactive_tab_foreground #606060
inactive_tab_background #1a1a1a
tab_bar_background #101010

active_border_color #859ba2
inactive_border_color #2e2e2e
