packages:
  fonts:
    - ttf-comfortaa
    - ttf-courier-code
    - ttf-fira-sans
    - ttf-firacode-nerd
    - ttf-hack-nerd
    - ttf-hannom
    - ttf-ibm-plex
    - ttf-indic-otf
    - ttf-intel-one-mono
    - ttf-iosevka-nerd
    - ttf-jetbrains-mono-nerd
    - ttf-kopub
    - ttf-lato
    - ttf-linux-libertine
    - otf-monaspace
    - ttf-nerd-fonts-symbols
    - ttf-nerd-fonts-symbols-common
    - ttf-nerd-fonts-symbols-mono
    - noto-fonts-emoji
    - adobe-source-code-pro-fonts

  shell_tools:
    - zsh
    - tmux
    - fzf
    - git
    - github-cli
    - kubectl
    - xclip
    - bat
    - libnotify
    - dbus
    - procps-ng
    - newsraft
    - tex-fmt
    - xsettingsd
    - pciutils

  archives:
    - lrzip
    - unrar
    - unzip
    - zip
    - unace
    - p7zip
    - squashfs-tools
    - tar
    - 7zip

  graphics_common:
    - mesa
    - mesa-utils
    - vulkan-mesa-layers
    - opencl-mesa
    - libva-utils

  gpu_amd:
    - vulkan-radeon
    - vulkan-amdgpu-pro

  gpu_intel:
    - vulkan-intel
    - intel-media-driver
    - libva-intel-driver

  cpu_amd:
    - amd-ucode

  cpu_intel:
    - intel-ucode
    - thermald

  hyprland:
    - hyprpolkitagent
    - hyprland
    - hyprshade
    - hyprlang
    - hyprcursor
    - hypridle
    - hyprlock
    - hyprpicker
    - xdg-desktop-portal-hyprland
    - xdg-desktop-portal-gtk
    - fuzzel
    - waybar
    - cliphist
    - grim
    - gvfs
    - gvfs-mtp
    - imagemagick
    - inxi
    - jq
    - network-manager-applet
    - pamixer
    - pavucontrol
    - pipewire-alsa
    - playerctl
    - pyprland
    - qt5ct
    - qt6ct
    - qt6-svg
    - slurp
    - swappy
    - swaync
    - awww
    - wallust
    - wl-clipboard
    - wlogout
    - xdg-user-dirs
    - xdg-utils
    - brightnessctl
    - pacman-contrib
    # Hyprland plugin build dependencies
    - cmake
    - meson
    - cpio

  programs:
    - antigravity
    - curl
    - wget
    - pcmanfm
    - xarchiver
    - yt-dlp
    - nwg-look
    - nvtop
    - mpv
    - mpv-mpris
    - imv
    - dunst
    - btop
    - fastfetch
    - gedit
    - kitty
    - kvantum
    - neovim-nightly
    - tree-sitter-cli
    - lazygit
    - bitwarden
    - ripgrep
    - bitwarden-cli
    - sioyek
    - docker
    - docker-compose
    - docker-buildx
    - exiftool

  obs:
    - obs-studio
    - ffmpeg
    - ffmpeg4.4

  system_services:
    - earlyoom
    - zram-generator
    - ananicy-cpp
    - irqbalance
