set-option -g default-terminal "screen-256color"
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
set-option -g allow-passthrough on
set-option -g default-command zsh
set-option -g extended-keys on
set -g visual-activity off
set-option -g focus-events on
set -s escape-time 0

# Main prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Toggle mouse on
bind-key M \
    set-option -g mouse on \;\
    display-message 'Mouse: ON'

# Toggle mouse off
bind-key m \
    set-option -g mouse off \;\
    display-message 'Mouse: OFF'

# Sort by name
bind s choose-tree -sZ -O name

# Change indices
set -g base-index 1
setw -g pane-base-index 1

# Key remapping
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

set-window-option -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'

unbind -T copy-mode-vi MouseDragEnd1Pane

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'

set -g @themepack 'powerline/'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize plugin manager
run '~/.tmux/plugins/tpm/tpm'
