Net/ThemeName "Redmond97 SE Jet Blue"
Net/IconThemeName "Silvery-Dark-Icons"
Gtk/CursorThemeName "SilverXMod"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintfull"
Xft/RGBA "rgb"
