---@module 'hl'

hl.config({
	master = {
		new_on_top = 1,
		mfact = 0.5,
	},
	general = {
		gaps_in = 5,
		gaps_out = 10,
		border_size = 2,
		resize_on_border = 1,
		extend_border_grab_area = 1,
		allow_tearing = 1,
		layout = "hy3",
		col = {
			active_border = "rgba(60606040)",
			inactive_border = "rgb(000000)",
		},
	},
	decoration = {
		rounding = 5,
		active_opacity = 1.0,
		fullscreen_opacity = 1.0,
		dim_inactive = 0,
		dim_strength = 0,
		screen_shader = "./shaders/vibrance.glsl.mustache",
		shadow = {
			enabled = 0,
		},
		blur = {
			enabled = 1,
		},
	},
	animations = {
		enabled = 0,
	},
	input = {
		kb_layout = "us,ru",
		kb_options = "grp:alt_shift_toggle,compose:rctrl,ctrl:swapcaps",
		follow_mouse = 1,
		float_switch_override_focus = 0,
		repeat_rate = 30,
		repeat_delay = 150,
		numlock_by_default = 0,
		accel_profile = "flat",
		force_no_accel = 0,
		sensitivity = 0,
		scroll_method = "on_button_down",
		scroll_factor = 1,
		focus_on_close = 0,
		mouse_refocus = 0,
		touchpad = {
			disable_while_typing = 1,
			scroll_factor = 2,
		},
	},
	misc = {
		disable_hyprland_logo = 1,
		disable_splash_rendering = 1,
		mouse_move_enables_dpms = 1,
		enable_swallow = 1,
		focus_on_activate = 1,
		swallow_regex = "^(kitty)$",
		font_family = "IBM Plex Sans",
	},
	cursor = {
		no_warps = 1,
		sync_gsettings_theme = 1,
		no_hardware_cursors = 2,
		enable_hyprcursor = 1,
	},
	ecosystem = {
		no_donation_nag = 1,
		no_update_news = 0,
	},
	xwayland = {
		force_zero_scaling = 1,
	},
	plugin = {
		-- 	hy3 = {
		-- 		node_collapse_policy = 2,
		-- 		group_inset = 10,
		-- 		tab_first_window = false,
		-- 		tabs = {
		-- 			height = 22,
		-- 			padding = 6,
		-- 			from_top = false,
		-- 			radius = 6,
		-- 			border_width = 2,
		-- 			render_text = true,
		-- 			text_center = true,
		-- 			text_font = "IBM Plex Sans",
		-- 			text_height = 8,
		-- 			text_padding = 3,
		-- 			colors = {
		-- 				active = "rgba(60606040)",
		-- 				active_border = "rgba(808080ee)",
		-- 				active_text = "rgba(ffffffff)",
		-- 				active_alt_monitor = "rgba(00000040)",
		-- 				active_alt_monitor_border = "rgba(333333ee)",
		-- 				active_alt_monitor_text = "rgba(ffffffff)",
		-- 				focused = "rgba(808080ee)",
		-- 				focused_border = "rgba(60606040)",
		-- 				focused_text = "rgba(ffffffff)",
		-- 				inactive_monitor = "rgba(808080ee)",
		-- 				inactive_border = "rgba(60606040)",
		-- 				inactive_text = "rgba(ffffffff)",
		-- 				urgent = "rgba(ff223340)",
		-- 				urgent_border = "rgba(ff2233ee)",
		-- 				urgent_text = "rgba(ffffffff)",
		-- 				locked = "rgba(90903340)",
		-- 				locked_border = "rgba(909033ee)",
		-- 				locked_text = "rgba(ffffffff)",
		-- 			},
		-- 			blur = true,
		-- 			opacity = 1.0,
		-- 		},
		-- 		autotile = {
		-- 			enable = true,
		-- 			ephemeral_groups = true,
		-- 			trigger_width = 0,
		-- 			trigger_height = 0,
		-- 			workspaces = "all",
		-- 		},
		-- 	},
	},
})
