# Sourcing external config files

exec-once = $HOME/.config/hypr/initial-boot.sh

# User Configs
$configs = $HOME/.config/hypr/configs

source=$configs/env-variables.conf
source=$configs/window-rules.conf
source=$configs/monitors.conf
source=$configs/user-settings.conf
source=$configs/user-keybinds.conf
source=$configs/startup-apps.conf
