#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Apply themes in Bspwm

CFG="$HOME/.config"
BSP="$HOME/.config/bspwm"
XRES="$HOME/.Xresources.d"

## Set Style
set_style () {
	
	# apply color-scheme
	cat "$BSP"/themes/${1} > "$XRES"/colors
	
	# reload config
	bspc wm -r
}

set_style "${1}"
