# Shell variables
# Generated by 'wal'
wallpaper='/home/notrodans/Pictures/wallpapers/Fantasy-Autumn.png'

# Special
background='#131219'
foreground='#ddccde'
cursor='#ddccde'

# Colors
color0='#131219'
color1='#633E81'
color2='#68688D'
color3='#906DA1'
color4='#7987A7'
color5='#9196B2'
color6='#ADAFC8'
color7='#ddccde'
color8='#9a8e9b'
color9='#633E81'
color10='#68688D'
color11='#906DA1'
color12='#7987A7'
color13='#9196B2'
color14='#ADAFC8'
color15='#ddccde'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
