--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/notrodans/Pictures/wallpapers/Fantasy-Autumn.png"

-- Special
background="#131219"
foreground="#ddccde"
cursor="#ddccde"

-- Colors
color0="#131219"
color1="#633E81"
color2="#68688D"
color3="#906DA1"
color4="#7987A7"
color5="#9196B2"
color6="#ADAFC8"
color7="#ddccde"
color8="#9a8e9b"
color9="#633E81"
color10="#68688D"
color11="#906DA1"
color12="#7987A7"
color13="#9196B2"
color14="#ADAFC8"
color15="#ddccde"
