#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## launch alacritty with bspwm config

# bspwm directory
DIR="$HOME/.config"
CONFIG="$DIR/kitty/kitty.conf"

kitty --config $CONFIG
